#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
#
# variables
if [ $# -lt 4 ]
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
#else
#  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
path_to_filr=$1
ip=$2
username=$3
path_to_ssh_key=$4

