#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update
sudo apt-get install nginx -y
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
# Creating new index
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
# Set up a 404 page
sudo mkdir -p /var/www/azzaomer.tech/html
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/azzaomer.tech/html/custom_404.html > /dev/null
# Setting up /redirect_me to google
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.google.com/;\n\t}' /etc/nginx/sites-available/default
# Set up a 404 page
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/azzaomer.tech/html;\n\t}' /etc/nginx/sites-available/default
# Restarting nginx
sudo service nginx start
sudo nginx -s reload
echo -e "\nCompleted.\n"
