#!/usr/bin/env bash
# Script to install and configure Nginx with a custom header

# Update package lists
sudo apt-get update

# Install Nginx web server
sudo apt-get install nginx -y

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a default HTML page with "Hello World!" content
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html' > /dev/null 2>&1

# Create a custom directory for the custom 404 page
sudo mkdir -p /var/www/abeermosaad.tech/html

# Create a custom 404 error page with French content
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/azzaomer.tech/html/custom_404.html > /dev/null 2>&1

# Add a redirect location to the Nginx configuration
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.google.com/;\n\t}' /etc/nginx/sites-available/default

# Configure custom 404 error page in the Nginx configuration
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/azzaomer.tech/html;\n\t}' /etc/nginx/sites-available/default

# Add a custom header to the Nginx responses
sudo sed -i "/^server {/a \ \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
