#!/usr/bin/env bash
# Install and configure HAproxy load palancer
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
    balance roundrobin
    server 198370-web-01 34.207.227.199:80
    server 198370-web-02 18.207.112.145:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null 2>&1
sudo service haproxy restart
