#!/usr/bin/env bash
# Debug find out what’s keeping your 
# Ubuntu container’s Nginx installation from listening on port 80
# sed -i 's/8080/80/g'
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
