#!/usr/bin/env bash

# Initialize the counter variable
count=1

# Loop until the counter exceeds 10
until [ $count -gt 10 ]
do
    echo "Best School"
    # Increment the counter to avoid an infinite loop
    count=$((count + 1))
done

