#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with:
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8.
# cp /etc/hosts/ ~/hpsts.new
# sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
# echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
# cat ~/hosts.new > /etc/hosts
